name: Vite Github Pages Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master", "main"]
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 查看node版本
        run: node -v
      - name: 安装依赖打包
        run: |
          npm install
          npm run build
      - name: 部署
       
      
